# serviceaccount
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-admin
  namespace: 10_namespace-template
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile