# configmap
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: configmap-nginx-conf
  namespace: icql-static
  labels:
    app: configmap-nginx-conf
data:
  nginx.conf: |
    user  nginx;
    worker_processes  1;
    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;
    events {
        worker_connections  1024;
    }
    http {
        default_type  application/octet-stream;
        map $sent_http_content_type $charset {
          ~^text/   utf-8;
        }
        charset       $charset;
        charset_types *;
        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';
        access_log  /var/log/nginx/access.log  main;
        sendfile        on;
        keepalive_timeout  65;
        gzip  on;
        include       /static/conf/icql-static/nginx/conf/mime.types;
        server {
                listen       80;
                server_name  localhost;
                charset utf-8;
                location / {
                    root   /static/00_home/public;
                    index  index.html;
                }
        }
        server {
                listen       81;
                server_name  127.0.0.1;
                charset utf-8;
                location / {
                    root   /static/01_archive;
                    autoindex on;
                    autoindex_format html;
                    autoindex_exact_size off;
                    autoindex_localtime on;
                }
        }
        server {
                listen       82;
                server_name  127.0.0.1;
                charset utf-8;
                location / {
                    root   /static/02_file;
                    index  index.html index.htm;
                }
        }
    }
