# configmap
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: configmap-mysql-conf
  namespace: icql-svc
  labels:
    app: configmap-mysql-conf
data:
  my.cnf: |
    [mysqld]
    character-set-server=utf8
    default-time-zone='+08:00'
    [client]
    default-character-set=utf8
    [mysql]
    default-character-set=utf8